# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/divyanshu/Desktop/CITS3003/labs-examples/project/CITS3003_Project_Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/divyanshu/Desktop/CITS3003/labs-examples/project/CITS3003_Project_Template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\" \"assimp-dev\" \"libassimp5.0.1-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/divyanshu/Desktop/CITS3003/labs-examples/project/CITS3003_Project_Template/CMakeFiles /home/divyanshu/Desktop/CITS3003/labs-examples/project/CITS3003_Project_Template/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/divyanshu/Desktop/CITS3003/labs-examples/project/CITS3003_Project_Template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named start_scene

# Build rule for target.
start_scene: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 start_scene
.PHONY : start_scene

# fast build rule for target.
start_scene/fast:
	$(MAKE) -f CMakeFiles/start_scene.dir/build.make CMakeFiles/start_scene.dir/build
.PHONY : start_scene/fast

#=============================================================================
# Target rules for targets named libglew_static

# Build rule for target.
libglew_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libglew_static
.PHONY : libglew_static

# fast build rule for target.
libglew_static/fast:
	$(MAKE) -f lib/glew/CMakeFiles/libglew_static.dir/build.make lib/glew/CMakeFiles/libglew_static.dir/build
.PHONY : libglew_static/fast

#=============================================================================
# Target rules for targets named freeglut_static

# Build rule for target.
freeglut_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freeglut_static
.PHONY : freeglut_static

# fast build rule for target.
freeglut_static/fast:
	$(MAKE) -f lib/freeglut/freeglut/freeglut/CMakeFiles/freeglut_static.dir/build.make lib/freeglut/freeglut/freeglut/CMakeFiles/freeglut_static.dir/build
.PHONY : freeglut_static/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f lib/assimp/code/CMakeFiles/assimp.dir/build.make lib/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named bitmap

# Build rule for target.
bitmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bitmap
.PHONY : bitmap

# fast build rule for target.
bitmap/fast:
	$(MAKE) -f lib/bitmap/CMakeFiles/bitmap.dir/build.make lib/bitmap/CMakeFiles/bitmap.dir/build
.PHONY : bitmap/fast

#=============================================================================
# Target rules for targets named angel

# Build rule for target.
angel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 angel
.PHONY : angel

# fast build rule for target.
angel/fast:
	$(MAKE) -f lib/angel/CMakeFiles/angel.dir/build.make lib/angel/CMakeFiles/angel.dir/build
.PHONY : angel/fast

src/scene-start.o: src/scene-start.cpp.o

.PHONY : src/scene-start.o

# target to build an object file
src/scene-start.cpp.o:
	$(MAKE) -f CMakeFiles/start_scene.dir/build.make CMakeFiles/start_scene.dir/src/scene-start.cpp.o
.PHONY : src/scene-start.cpp.o

src/scene-start.i: src/scene-start.cpp.i

.PHONY : src/scene-start.i

# target to preprocess a source file
src/scene-start.cpp.i:
	$(MAKE) -f CMakeFiles/start_scene.dir/build.make CMakeFiles/start_scene.dir/src/scene-start.cpp.i
.PHONY : src/scene-start.cpp.i

src/scene-start.s: src/scene-start.cpp.s

.PHONY : src/scene-start.s

# target to generate assembly for a file
src/scene-start.cpp.s:
	$(MAKE) -f CMakeFiles/start_scene.dir/build.make CMakeFiles/start_scene.dir/src/scene-start.cpp.s
.PHONY : src/scene-start.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... start_scene"
	@echo "... libglew_static"
	@echo "... freeglut_static"
	@echo "... assimp"
	@echo "... bitmap"
	@echo "... angel"
	@echo "... src/scene-start.o"
	@echo "... src/scene-start.i"
	@echo "... src/scene-start.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

